name: poi .net core testing

on:
  push:
    paths:
    - 'apis/poi/**'
    - '.github/workflows/dotnetworkflow.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup .NET Core SDK 2
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.103
    - uses: actions/checkout@v2
    - name: Running dotnet tests
      working-directory: ./apis/poi/
      run: dotnet test
    - name: Create issue from failure of test
      if: ${{ failure() }}
      uses: peter-evans/create-issue-from-file@v2
      with: 
        title: Build failed
        content-filepath: ./apis/poi/issuecontent.md
        labels: sre, cloud
        assignees: shwsrini, toddwhitehead
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: 'Checkout GitHub Action' 
      uses: actions/checkout@master
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.SERVICE_PRINCE }}
    
    - uses: azure/docker-login@v1
      with:
        login-server: openhackjy29oiq3acr.azurecr.io
        username: ${{ secrets.USER_NAME }}
        password: ${{ secrets.PASSWORD }}
    
    - run: |
        docker build . -t openhackjy29oiq3acr.azurecr.io/devopsoh/api-poi:${{ github.run_number }}
        docker push openhackjy29oiq3acr.azurecr.io/devopsoh/api-poi:${{ github.run_number }}
