name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/download-artifact@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - working-directory: ./apis/userprofile/
      run: npm install
    
    - working-directory: ./apis/userprofile/
      run: npm run build --if-present

    - working-directory: ./apis/userprofile/
      run: npm test
      

      env:
        CI: true