name: poi .net core testing

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.103
    - uses: actions/checkout@v2
    - name: Testing build
      working-directory: ./apis/poi/
      run: dotnet test
