name: poi .net core testing

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Testing build
      working-directory: /apis/poi/
      run: dotnet test