name: poi .net core testing

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      DOTNET_VERSION: '3.1.103' 
    steps:
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }} 
    - uses: actions/checkout@v2
    - name: Testing build
      working-directory: /apis/poi/
      run: dotnet test