name: poi .net core testing

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.103
    - uses: actions/download-artifact@v2
    - name: Running Tests
      working-directory: ./apis/poi/
      run: dotnet test
